### ISSUE TITLE
Module freebox provoque une erreur

### ISSUE THREAD

**Issue by Admyst** [Lyreo/gladys-freebox#2]
Lors de l'installation du module freebox, l'installation n'est jamais marquée comme terminée et dans le log une erreur apparait :

 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|gladys   | TypeError: Cannot read property 'then' of undefined
0|gladys   |     at execInstallFunction (/home/pi/gladys/api/core/module/module.init.js:42:6)
0|gladys   |     at /home/pi/gladys/api/core/module/module.init.js:17:21
0|gladys   |     at tryCatcher (/home/pi/gladys/node_modules/bluebird/js/release/util.js:16:23)
0|gladys   |     at MappingPromiseArray._promiseFulfilled (/home/pi/gladys/node_modules/bluebird/js/release/map.js:61:38)
0|gladys   |     at MappingPromiseArray.PromiseArray._iterate (/home/pi/gladys/node_modules/bluebird/js/release/promise_array.js:114:31)
0|gladys   |     at MappingPromiseArray.init (/home/pi/gladys/node_modules/bluebird/js/release/promise_array.js:78:10)
0|gladys   |     at MappingPromiseArray._asyncInit (/home/pi/gladys/node_modules/bluebird/js/release/map.js:30:10)
0|gladys   |     at Async._drainQueue (/home/pi/gladys/node_modules/bluebird/js/release/async.js:138:12)
0|gladys   |     at Async._drainQueues (/home/pi/gladys/node_modules/bluebird/js/release/async.js:143:10)
0|gladys   |     at Immediate.Async.drainQueues (/home/pi/gladys/node_modules/bluebird/js/release/async.js:17:14)
0|gladys   |     at runCallback (timers.js:789:20)
0|gladys   |     at tryOnImmediate (timers.js:751:5)
0|gladys   |     at processImmediate [as _immediateCallback] (timers.js:722:5)
0|gladys   | Gladys is up to date !

**Comment by NickDub-old** [comment]
C'est un doublon de l'issue que j'ai ouvert #1 .
